<a href="https://colab.research.google.com/github/DanishCH/Mastering_Pandas/blob/main/Pandas_subset_selection_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**Reverse Row order**

In [85]:
df.loc[::-1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False

In [86]:
df.head(-6)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True

In [87]:
df.loc[::-1].reset_index(drop=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
1,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
2,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
3,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
4,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
888,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
889,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
890,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False

### Understanding `reset_index(drop=True)` with an example

First, let's create a small DataFrame to play with:

In [88]:
import pandas as pd

# Create a simple DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df_example = pd.DataFrame(data)
df_example.index = [10, 20, 30] # Give it a custom, non-sequential index
print('Original DataFrame:')
display(df_example)

Original DataFrame:

       Name  Age
10    Alice   25
20      Bob   30
30  Charlie   35

Now, let's reverse the rows of this DataFrame. Notice how the index (the numbers on the far left) gets jumbled, but still refers to the original row numbers:

In [89]:
df_reversed = df_example.loc[::-1]
print('DataFrame after reversing rows (index is now out of order):')
display(df_reversed)

DataFrame after reversing rows (index is now out of order):

       Name  Age
30  Charlie   35
20      Bob   30
10    Alice   25

### `reset_index()` without `drop=True`

If we just use `reset_index()` without `drop=True`, Pandas creates a *new* default index (0, 1, 2...) but *keeps* the old, jumbled index as a new column called 'index'. This can sometimes be confusing or create an unnecessary column.

In [90]:
df_reset_without_drop = df_reversed.reset_index()
print('DataFrame after reset_index() WITHOUT drop=True (old index becomes a column):')
display(df_reset_without_drop)

DataFrame after reset_index() WITHOUT drop=True (old index becomes a column):

   index     Name  Age
0     30  Charlie   35
1     20      Bob   30
2     10    Alice   25

### `reset_index(drop=True)`

Now, if we add `drop=True`, Pandas will still create a new, clean default index (0, 1, 2...) but it will **completely get rid of the old index**. It "drops" the old index instead of turning it into a new column. This is often what you want when you've reordered your data and just need a fresh start with your row numbers.

In [91]:
df_reset_with_drop = df_reversed.reset_index(drop=True)
print('DataFrame after reset_index() WITH drop=True (old index is gone):')
display(df_reset_with_drop)

DataFrame after reset_index() WITH drop=True (old index is gone):

      Name  Age
0  Charlie   35
1      Bob   30
2    Alice   25

In summary:

*   `reset_index()`: Gives you a new, clean index, but keeps the old index as a new column.
*   `reset_index(drop=True)`: Gives you a new, clean index, and throws away the old index completely.

## Understanding `.loc` vs. `.iloc`

In pandas, both `.loc` and `.iloc` are used for selecting data from a DataFrame, but they do so in fundamentally different ways:

### `.loc` (Label-based indexing)

*   **Definition**: `.loc` is primarily label-based. This means you select data based on the *labels* (names) of rows and columns.
*   **Usage**: You pass the actual index labels for rows and column names for columns.
*   **Key Feature**: Includes the end label when slicing. If you slice `df.loc[start_label:end_label]`, both `start_label` and `end_label` are included in the result.
*   **Common Use Cases**: When you know the specific labels of the rows or columns you want to access, or when filtering by boolean conditions on labels.

In [92]:
# Let's use our df_example:
print('Original DataFrame:')
display(df_example)

# Example 1: Selecting a specific row by its label (index)
print('\nSelecting row with label 20 using .loc:')
display(df_example.loc[20])

# Example 2: Selecting multiple rows by labels
print('\nSelecting rows with labels 10 and 30 using .loc:')
display(df_example.loc[[10, 30]])

# Example 3: Selecting a slice of rows by labels (inclusive)
print('\nSelecting rows from label 10 to 30 (inclusive) using .loc:')
display(df_example.loc[10:30])

# Example 4: Selecting specific rows and columns by labels
print("\nSelecting row 20 and the 'Name' column using .loc:")
display(df_example.loc[20, 'Name'])

# Example 5: Selecting a slice of rows and specific columns by labels
print("\nSelecting rows 10 to 20 and 'Name', 'Age' columns using .loc:")
display(df_example.loc[10:20, ['Name', 'Age']])

# Example 6: Filtering rows using a boolean condition (label-based)
print('\nSelecting rows where Age is greater than 25 using .loc:')
display(df_example.loc[df_example['Age'] > 25])

Original DataFrame:

       Name  Age
10    Alice   25
20      Bob   30
30  Charlie   35

Selecting row with label 20 using .loc:

Name    Bob
Age      30
Name: 20, dtype: object

Selecting rows with labels 10 and 30 using .loc:

       Name  Age
10    Alice   25
30  Charlie   35

Selecting rows from label 10 to 30 (inclusive) using .loc:

       Name  Age
10    Alice   25
20      Bob   30
30  Charlie   35

Selecting row 20 and the 'Name' column using .loc:

'Bob'

Selecting rows 10 to 20 and 'Name', 'Age' columns using .loc:

     Name  Age
10  Alice   25
20    Bob   30

Selecting rows where Age is greater than 25 using .loc:

       Name  Age
20      Bob   30
30  Charlie   35

### `.iloc` (Integer-location based indexing)

*   **Definition**: `.iloc` is primarily integer-location based. This means you select data based on the *numerical position* of rows and columns (just like in standard Python list indexing).
*   **Usage**: You pass integer positions (0-based) for rows and columns.
*   **Key Feature**: Exclusive of the end position when slicing. If you slice `df.iloc[start_position:end_position]`, the `end_position` is *not* included in the result (similar to Python list slicing).
*   **Common Use Cases**: When you need to select data based on its absolute position, or when iterating through rows/columns by their index number.

In [93]:
# Let's use our df_example again:
print('Original DataFrame:')
display(df_example)

# Example 1: Selecting a specific row by its integer position (0-based)
print('\nSelecting the row at integer position 1 (which has label 20) using .iloc:')
display(df_example.iloc[1])

# Example 2: Selecting multiple rows by integer positions
print('\nSelecting rows at integer positions 0 and 2 using .iloc:')
display(df_example.iloc[[0, 2]])

# Example 3: Selecting a slice of rows by integer positions (exclusive of end)
print('\nSelecting rows from integer position 0 up to (but not including) 2 using .iloc:')
display(df_example.iloc[0:2])

# Example 4: Selecting specific rows and columns by integer positions
print("\nSelecting row at position 1 and column at position 0 ('Name') using .iloc:")
display(df_example.iloc[1, 0])

# Example 5: Selecting a slice of rows and specific columns by integer positions
print('\nSelecting rows from 0 to 2 (exclusive) and columns 0 to 2 (exclusive) using .iloc:')
display(df_example.iloc[0:2, 0:2])

# Example 6: Selecting all rows and the first column by integer position
print("\nSelecting all rows and the column at integer position 0 ('Name') using .iloc:")
display(df_example.iloc[:, 0])

Original DataFrame:

       Name  Age
10    Alice   25
20      Bob   30
30  Charlie   35

Selecting the row at integer position 1 (which has label 20) using .iloc:

Name    Bob
Age      30
Name: 20, dtype: object

Selecting rows at integer positions 0 and 2 using .iloc:

       Name  Age
10    Alice   25
30  Charlie   35

Selecting rows from integer position 0 up to (but not including) 2 using .iloc:

     Name  Age
10  Alice   25
20    Bob   30

Selecting row at position 1 and column at position 0 ('Name') using .iloc:

'Bob'

Selecting rows from 0 to 2 (exclusive) and columns 0 to 2 (exclusive) using .iloc:

     Name  Age
10  Alice   25
20    Bob   30

Selecting all rows and the column at integer position 0 ('Name') using .iloc:

10      Alice
20        Bob
30    Charlie
Name: Name, dtype: object


*   **`.loc`** uses the actual `index labels` (e.g., `101`, `102`, `103`) and `column names` (e.g., `'age'`, `'fare'`). Notice how slicing `101:103` includes `103`.
*   **`.iloc`** uses the `integer positions` (e.g., `1`, `2`, `3`) for both rows and columns. Notice how slicing `1:4` includes positions `1`, `2`, and `3`, but not `4`.

# **`Rverse` The column with .loc**

In [94]:
titanic_data = df.head(12)
display(titanic_data)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [95]:
titanic_data.iloc[:,::-1]

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,False,no,Southampton,NaN,True,man,Third,S,7.2500,0,1,22.0,male,3,0
1,False,yes,Cherbourg,C,False,woman,First,C,71.2833,0,1,38.0,female,1,1
2,True,yes,Southampton,NaN,False,woman,Third,S,7.9250,0,0,26.0,female,3,1
3,False,yes,Southampton,C,False,woman,First,S,53.1000,0,1,35.0,female,1,1
4,True,no,Southampton,NaN,True,man,Third,S,8.0500,0,0,35.0,male,3,0
5,True,no,Queenstown,NaN,True,man,Third,Q,8.4583,0,0,NaN,male,3,0
6,True,no,Southampton,E,True,man,First,S,51.8625,0,0,54.0,male,1,0
7,False,no,Southampton,NaN,False,child,Third,S,21.0750,1,3,2.0,male,3,0
8,False,yes,Southampton,NaN,False,woman,Third,S,11.1333,2,0,27.0,female,3,1
9,False,yes,Cherbourg,NaN,False,child,Second,C,30.0708,0,1,14.0,female,2,1
10,False,yes,Southampton,G,False,child,Third,S,16.7000,1,1,4.0,female,3,1
11,True,yes,Southampton,C,False,woman,First,S,26.5500,0,0,58.0,female,1,1

In [96]:
titanic_data.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [97]:
# Select columns using dtype
titanic_data.select_dtypes(include=['object'])

       sex embarked    who  embark_town alive
0     male        S    man  Southampton    no
1   female        C  woman    Cherbourg   yes
2   female        S  woman  Southampton   yes
3   female        S  woman  Southampton   yes
4     male        S    man  Southampton    no
5     male        Q    man   Queenstown    no
6     male        S    man  Southampton    no
7     male        S  child  Southampton    no
8   female        S  woman  Southampton   yes
9   female        C  child    Cherbourg   yes
10  female        S  child  Southampton   yes
11  female        S  woman  Southampton   yes

In [98]:
display(titanic_data.select_dtypes(include=['float64',"int64"]))  #selecting with Multiple datatype

    survived  pclass   age  sibsp  parch     fare
0          0       3  22.0      1      0   7.2500
1          1       1  38.0      1      0  71.2833
2          1       3  26.0      0      0   7.9250
3          1       1  35.0      1      0  53.1000
4          0       3  35.0      0      0   8.0500
5          0       3   NaN      0      0   8.4583
6          0       1  54.0      0      0  51.8625
7          0       3   2.0      3      1  21.0750
8          1       3  27.0      0      2  11.1333
9          1       2  14.0      1      0  30.0708
10         1       3   4.0      1      1  16.7000
11         1       1  58.0      0      0  26.5500

In [99]:
titanic_data.select_dtypes(exclude=["bool"]) #excluding bool datatype in column

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,deck,embark_town,alive
0,0,3,male,22.0,1,0,7.2500,S,Third,man,NaN,Southampton,no
1,1,1,female,38.0,1,0,71.2833,C,First,woman,C,Cherbourg,yes
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,NaN,Southampton,yes
3,1,1,female,35.0,1,0,53.1000,S,First,woman,C,Southampton,yes
4,0,3,male,35.0,0,0,8.0500,S,Third,man,NaN,Southampton,no
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,NaN,Queenstown,no
6,0,1,male,54.0,0,0,51.8625,S,First,man,E,Southampton,no
7,0,3,male,2.0,3,1,21.0750,S,Third,child,NaN,Southampton,no
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,NaN,Southampton,yes
9,1,2,female,14.0,1,0,30.0708,C,Second,child,NaN,Cherbourg,yes
10,1,3,female,4.0,1,1,16.7000,S,Third,child,G,Southampton,yes
11,1,1,female,58.0,0,0,26.5500,S,First,woman,C,Southampton,yes

# **Data Type Conversion**

In [100]:
df_frame = pd.DataFrame({"col_A" : [1,2,3,4,5,6],
                        "col_B" : [0.1,0.2 ,0.3, 0.4, 0.5, 0.6]})
df_frame.dtypes

col_A      int64
col_B    float64
dtype: object

In [101]:
df_frame

   col_A  col_B
0      1    0.1
1      2    0.2
2      3    0.3
3      4    0.4
4      5    0.5
5      6    0.6

In [105]:
#conversion float into integer
df_frame.astype({"col_A" : "float64","col_B" : "int64"}).dtypes

### Type Conversion with `astype()`

The `astype()` method is used to cast a pandas object to a specified data type. It's very flexible and can be applied to an entire DataFrame, a specific column, or multiple columns.

**Key Points:**

1.  **How it works**: You pass a dictionary to `astype()` where keys are column names and values are the desired data types (e.g., `'int'`, `'float'`, `'str'`, `'datetime64[ns]'`).
2.  **Returns a *new* DataFrame**: `astype()` does not modify the DataFrame in place. It returns a *new* DataFrame with the types converted. If you want to apply the changes to your original DataFrame, you need to assign the result back to it (e.g., `df = df.astype(...)`).
3.  **Error Handling**: If a conversion is not possible (e.g., trying to convert a string 'abc' to an integer), it will raise an error unless you specify `errors='coerce'`, which will turn unconvertible values into `NaN` (Not a Number).

Let's continue with the `df_frame` we just created to see this in action.

In [108]:
# Original DataFrame and its types
print("Original df_frame:")
display(df_frame)
print("Original Data Types:")
display(df_frame.dtypes)

# Convert 'col_A' to float and 'col_B' to integer
df_converted = df_frame.astype({"col_A": "float64", "col_B": "int64"})

print("\nDataFrame after type conversion (new DataFrame):")
display(df_converted)

print("Converted Data Types:")
display(df_converted.dtypes)

# Show that the original df_frame remains unchanged
print("\nOriginal df_frame data types (still unchanged):")
display(df_frame.dtypes)

Original df_frame:

   col_A  col_B
0      1    0.1
1      2    0.2
2      3    0.3
3      4    0.4
4      5    0.5
5      6    0.6

Original Data Types:

col_A      int64
col_B    float64
dtype: object

DataFrame after type conversion (new DataFrame):

   col_A  col_B
0    1.0      0
1    2.0      0
2    3.0      0
3    4.0      0
4    5.0      0
5    6.0      0

Converted Data Types:

col_A    float64
col_B      int64
dtype: object

Original df_frame data types (still unchanged):

col_A      int64
col_B    float64
dtype: object

### Error Handling with `astype()` and `errors='coerce'`

Let's create a new DataFrame with a column that has mixed data, including a string that can't be converted to a number. Then, we'll try to convert it to a numeric type.

In [109]:
# Create a DataFrame with a challenging column
df_mixed = pd.DataFrame({
    'numeric_col': [10, 20, 30, 'forty', 50],
    'other_col': ['A', 'B', 'C', 'D', 'E']
})

print("Original df_mixed:")
display(df_mixed)
print("Original Data Types:")
display(df_mixed.dtypes)

print("\nAttempting to convert 'numeric_col' to int without error handling (this will raise an error):")
try:
    df_mixed['numeric_col'].astype(int)
except ValueError as e:
    print(f"Caught an error: {e}")
    print("As you can see, directly converting 'forty' to an integer causes a ValueError.")

Original df_mixed:

  numeric_col other_col
0          10         A
1          20         B
2          30         C
3       forty         D
4          50         E

Original Data Types:

numeric_col    object
other_col      object
dtype: object

Attempting to convert 'numeric_col' to int without error handling (this will raise an error):
Caught an error: invalid literal for int() with base 10: 'forty'
As you can see, directly converting 'forty' to an integer causes a ValueError.

To handle such errors gracefully, we can use the `errors='coerce'` argument. When `errors='coerce'` is used, any values that cannot be converted to the target data type will be replaced with `NaN` (Not a Number), which is a special float value representing missing or undefined data.

In [110]:
print("\nConverting 'numeric_col' to numeric with errors='coerce':")
df_mixed['numeric_col_converted'] = pd.to_numeric(df_mixed['numeric_col'], errors='coerce')

# Note: pd.to_numeric is often preferred over .astype() when coercing errors
# because .astype() only supports 'raise' or 'ignore' (deprecated) for errors.
# While .astype() *can* be used with a custom error handling function, pd.to_numeric
# provides the 'coerce' option directly and is commonly used for this purpose.

print("df_mixed after coercing errors:")
display(df_mixed)
print("Data Types after coercing errors:")
display(df_mixed.dtypes)

print("Notice how 'forty' has been converted to NaN in the new column.")

Converting 'numeric_col' to numeric with errors='coerce':
df_mixed after coercing errors:

  numeric_col other_col  numeric_col_converted
0          10         A                   10.0
1          20         B                   20.0
2          30         C                   30.0
3       forty         D                    NaN
4          50         E                   50.0

Data Types after coercing errors:

numeric_col               object
other_col                 object
numeric_col_converted    float64
dtype: object

Notice how 'forty' has been converted to NaN in the new column.

# **`Extracting` Sample from dataset**

In [119]:
titanic_data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [121]:
titanic_data.sample(frac=0.5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [122]:
titanic_data.sample(frac=0.5).shape

(6, 15)