<a href="https://colab.research.google.com/github/DanishCH/Mastering_Pandas/blob/main/Pandas_Subset_Selection02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Copied Data From Clipboard**

In [2]:
import seaborn as sns
import pandas as pd

In [3]:
df_titanic = sns.load_dataset('titanic')
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df_titanic.to_csv("kashti.csv")

In [5]:
try:
    df_california_house = pd.read_clipboard()
    if df_california_house.empty:
        print("Warning: Clipboard is empty or contains no parsable data. df_california_house is an empty DataFrame.")
except Exception as e:
    print(f"Error reading clipboard: {e}")
    df_california_house = pd.DataFrame() # Define it as an empty DataFrame to avoid NameError
df_california_house

Error reading clipboard:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

Empty DataFrame
Columns: []
Index: []

In [6]:
len(df_titanic)

891

In [14]:
print(f"Loaded dataset {df_titanic.shape[0]} rows, {df_titanic.shape[1]} columns")

Loaded dataset 891 rows, 15 columns

In [8]:
# import numpy as np
# from sklearn.model_selection import train_test_split

# # --- Sequential Split ---
# # Calculate the midpoint for splitting
# midpoint = len(df_titanic) // 2

# # Split into two sequential DataFrames
# df_titanic_seq1 = df_titanic.iloc[:midpoint]
# df_titanic_seq2 = df_titanic.iloc[midpoint:]

# print("Sequential Split:")
# print(f"df_titanic_seq1 shape: {df_titanic_seq1.shape}")
# print(f"df_titanic_seq2 shape: {df_titanic_seq2.shape}")
# print("\n")

# # --- Random Split ---
# # Split into two random DataFrames (50/50 split)
# # Using random_state for reproducibility
# df_titanic_rand1, df_titanic_rand2 = train_test_split(df_titanic, test_size=0.5, random_state=42)

# print("Random Split:")
# print(f"df_titanic_rand1 shape: {df_titanic_rand1.shape}")
# print(f"df_titanic_rand2 shape: {df_titanic_rand2.shape}")

In [9]:
midpoint = df_titanic.shape[0] // 2
midpoint
# import numpy as np
df_titanic_seq1 = df_titanic.iloc[:445]
df_titanic_seq1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,1,2,female,45.0,1,1,26.2500,S,Second,woman,False,NaN,Southampton,yes,False
441,0,3,male,20.0,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
442,0,3,male,25.0,1,0,7.7750,S,Third,man,True,NaN,Southampton,no,False
443,1,2,female,28.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
444,1,3,male,NaN,0,0,8.1125,S,Third,man,True,NaN,Southampton,yes,True

In [10]:
df_titanic_seq2 = df_titanic.iloc[445:]
df_titanic_seq2

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
445,1,1,male,4.0,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
446,1,2,female,13.0,0,1,19.5000,S,Second,child,False,NaN,Southampton,yes,False
447,1,1,male,34.0,0,0,26.5500,S,First,man,True,NaN,Southampton,yes,True
448,1,3,female,5.0,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
449,1,1,male,52.0,0,0,30.5000,S,First,man,True,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [11]:
import random

In [12]:
# second way to split data with randomness
df_titanic_train = df_titanic.sample(frac=0.7, random_state=1)
df_titanic_train

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
223,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
84,1,2,female,17.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
680,0,3,female,NaN,0,0,8.1375,Q,Third,woman,False,NaN,Queenstown,no,True
535,1,2,female,7.0,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,0,3,male,18.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
240,0,3,female,NaN,1,0,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
230,1,1,female,35.0,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
458,1,2,female,50.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True

In [13]:
df_titanic_test = df_titanic.drop(df_titanic_train.index)
df_titanic_test

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [21]:
#combined both seprate data set in on frame
combined_titanic = pd.concat([df_titanic_train, df_titanic_test]).reset_index(drop=True)
combined_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
1,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
2,1,2,female,17.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
3,0,3,female,NaN,0,0,8.1375,Q,Third,woman,False,NaN,Queenstown,no,True
4,1,2,female,7.0,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
887,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
888,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
889,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
890,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [24]:
combined_titanic_reset = combined_titanic.reset_index(drop=True)
display(combined_titanic_reset.head())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
1,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
2,1,2,female,17.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
3,0,3,female,NaN,0,0,8.1375,Q,Third,woman,False,NaN,Queenstown,no,True
4,1,2,female,7.0,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False

In [25]:
#how many variable or types in the class column
combined_titanic['class'].unique()

['First', 'Third', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [28]:
#every types how many time in the  column
combined_titanic['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [32]:
# i want to see the data of passenger which are reserved first class
first_class_passengers = combined_titanic[combined_titanic["class"] == "First"]

In [39]:
#if i want to see data of male belongs to Queensland and their age is less then 30
df_titanic[(df_titanic.sex == "male") & (df_titanic.age < 30) & (df_titanic.embark_town == "Queenstown")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
143,0,3,male,19.0,0,0,6.7500,Q,Third,man,True,NaN,Queenstown,no,True
171,0,3,male,4.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
278,0,3,male,7.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
421,0,3,male,21.0,0,0,7.7333,Q,Third,man,True,NaN,Queenstown,no,True
510,1,3,male,29.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,yes,True
703,0,3,male,25.0,0,0,7.7417,Q,Third,man,True,NaN,Queenstown,no,True
787,0,3,male,8.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False